version: '3'
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_HOST: '%'
    volumes:
    - ./db/mysql_init.sql:/docker-entrypoint-initdb.d/mysql_init.sql
    ports:
    - "${DB_PORT}:3306"